INSERT INTO PRODUCTS (id, name, description) VALUES
     ('acf49189-e872-48b0-949e-63d455f4fd86', 'Merkurijus', 'Merkurijus (sen. lietuvių pavadinimai Vaivora, Pažarinis[1])  – artimiausia Saulei planeta, už kurios kita, toliau nuo Saulės esanti planeta, yra Venera. Merkurijus aplink Saulę skrieja ištęsta elipsine orbita (nuotolis nuo Saulės kinta nuo 46 iki 70 milijonų km), dėl to Saulės apšviestas paviršius įkaista iki 700 K (430 °C) perihelyje ir iki 560 K (290 °C) afelyje. Kadangi beveik neturi atmosferos, kuri išlaikytų šilumą, bei dėl ilgai trukančios Merkurijaus nakties temperatūra nukrinta iki 100 K (-163 °C) ties pusiauju.[2] Tuo tarpu poliariniuose regionuose temperatūra visąlaik išlieka neigiama (180 K, arba -93 °C). Merkurijaus skersmuo 2,6 karto, o masė 18 kartų mažesnė negu Žemės. Merkurijus apskrieja Saulę per 87,97 dienas, o apie ašį apsisuka per 58,647 dienos, todėl saulinė para jame trunka 175,942 Žemės dienas. Tai vienintelė planeta Saulės sistemoje, kurioje metų ir paros santykis 3:2'),
     ('7a580a64-a414-40dc-8861-52aa79ff2259', 'Venera', 'Venera (sen. lietuvių pavadinimai: Aušrinė, Vakarinė) – antroji pagal atstumą nuo Saulės planeta (tarp Merkurijaus ir Žemės).[1] Po Mėnulio tai – antrasis pagal šviesumą objektas naktiniame danguje (iki –4,6 ryškio), maksimumą pasiekiantis tuoj pat po saulėlydžio arba prieš pat saulėtekį.
                                                                             Planetos vardas siejamas su romėnų grožio ir meilės deive, tapačia senovės graikų Afroditei. Lietuviai ją laikė Saulės dukromis Vakarine ir Aušrine.
                                                                             Venera – vidinė Saulės sistemos planeta ir, žiūrint iš Žemės, nuo Saulės niekad nenutolsta toliau nei 47,8°. Ši planeta, turinti kietą dangą, kartais dar vadinama Žemės seserimi dėl dydžio ir sudėties panašumo. Venerą nuolat dengia storas nepermatomas, gerai šviesą atspindintis debesų sluoksnis, todėl įprastomis sąlygomis negalima pamatyti jos paviršiaus. Veneros atmosfera yra tankiausia iš Žemės tipo planetų, ją sudaro daugiausia anglies dioksidas, o atmosferos slėgis planetos paviršiuje yra 90 kartų didesnis nei Žemėje.
                                                                             Veneros paviršiaus žemėlapiai pradėti sudarinėti tik prieš 20 metų. Paviršiuje aptinkami vulkaninio aktyvumo požymiai ir gali būti, kad Veneros ugnikalniai iki šiol yra aktyvūs.'),
     ('7a580a64-a414-40dc-8861-52aa79ff2251', 'Žemė','Žemė – Saulės sistemos planeta. Pagal atstumą Žemė yra trečia nuo Saulės (tarp Veneros ir Marso) ir penkta pagal masę. Žemės amžius yra apie 4,57 mlrd. metų. Žemė yra vienintelė planeta Saulės sistemoje, turinti tokio sąlyginio dydžio palydovą − Mėnulį. Tai vienintelė žinoma planeta, kurioje egzistuoja gyvybė.'),
     ('7a580a64-a414-40dc-8861-52aa79ff2252', 'Marsas','Marsas (sen. lietuvių pavadinimas Žiezdrė) – ketvirtoji pagal atstumą nuo Saulės (tarp Žemės ir Jupiterio) ir antroji mažiausia Saulės sistemos planeta po Merkurijaus.
                                                                            Iš Žemės neretai matomas plika akimi kaip ryški rausvos spalvos žvaigždė. Vidutinis absoliutinis ryškis — +0,71, tačiau menamas ryškis gali siekti −2,94, ryškumu nusileidžiąs tik Venerai, Mėnuliui ir Saulei.[2] Dėl rausvo atspalvio žvelgiant iš Žemės kartais vadinama „raudonąja planeta“. Charakteringą spalvą Marsui suteikia trivalentis geležies oksidas, kurio gausu planetoje.[3] Planetos pavadinimas kilęs iš romėnų karo dievo Marso (graikų Arėjo atitikmuo). Atitinkamai pavadinti ir maži, netaisyklingos formos Marso palydovai Fobas ir Deimas, kurie graikų mitologijoje yra Arėjo sūnūs, lydintys jį mūšyje.[4]
                                                                            Dienos ir metų laikai Marse gali būti lyginami su Žeme dėl panašaus apsisukimo apie savo ašį periodo ir orbitos posvyrio į ekliptikos plokštumą. Vienerių Marso metų trukmė beveik dvigubai ilgesnė dėl didesnio atstumo iki Saulės. Marse yra Olimpas, didžiausias žinomas vulkanas Saulės sistemos planetoje, bei Marinerio slėnis, vienas didžiausių kanjonų Saulės sistemoje. Lygus Šiaurinis baseinas šiauriniame pusrutulyje užima 40% viso planetos paviršiaus ploto ir gali būti susidaręs po susidūrimo su stambiu dangaus kūnu.[5]
                                                                            Panašiai kaip priešdėlis geo- įvardinant su Žeme susijusius dalykus, Marso atveju kartais vartojamas priešdėlis areo-, pvz., areologija kaip geologijos atitikmuo arba areoidas vietoje geoido. Šis priešdėlis kildinamas iš graikų karo dievo Arėjo.'),
     ('7a580a64-a414-40dc-8861-52aa79ff2253', 'Jupiteris','Jupiteris (sen. lietuvių pavadinimas Indraja) – penktoji pagal nuotolį nuo Saulės sistemos planeta (tarp Marso ir Saturno), dujinė milžinė. Turi žiedų sistemą.
                                                                              Kaip ir kitos planetos, Jupiteris aplink Saulę skrieja ištęsta elipsine orbita, kurios viename židinyje yra Saulė. Nuotolis tarp Saulės ir Jupiterio kinta nuo 740 mln. iki 816 mln. km, Saulę apskrieja per 11,86 Žemės metų. Tai – didžiausia Saulės sistemos planeta, kurios skersmuo už Žemės didesnis 11 kartų, tūris – 1331 kartą, o masė – 317 kartų.
                                                                              Per opozicijas, kurios kartojasi kas 1,1 metų, Jupiteris danguje spindi kaip -2 ryškio gelsva žvaigždė. Pro teleskopą tuo metu jis atrodo kaip 45-50" dydžio skritulys, kurio paviršiuje nusidriekusios kelios lygiagrečios pusiaujui tamsesnės juostos.'),
     ('7a580a64-a414-40dc-8861-52aa79ff2254', 'Saturnas','Saturnas – antra pagal dydį (po Jupiterio) ir šešta pagal atstumą nuo Saulės planeta (tarp Jupiterio ir Urano).[1] Saturnas yra dujinė planeta milžinė, jos vidutinis skersmuo yra devynis kartus didesnis už Žemės.[2][3] Spėjama, kad Saturno vidų sudaro iš geležies ir nikelio bei silikatų uolienų sudarytas branduolys, apsuptas storu metalinio vandenilio sluoksniu, kurį savo ruožtu supa skysto helio sluoksnis. Planeta pavadinta romėnų turto ir žemdirbystės dievo vardu; ženklas (♄) vaizduoja pjautuvą.
                                                                              Saturnas nuo Saulės vidutiniškai nutolęs per 1429 milijonų km. Aplink Saulę apsisuka per 29,64 metus. Turi žiedų sistemą, sudarytą daugiausiai iš ledo dulkelių; taip pat yra uoliėnų nuolaužų ir kosminių dulkių. Turi bent 83 palydovus[4], iš kurių 53 turi pavadinimus, neįskaitant šimtų mažųjų palydovų, sutinkamų žieduose. Titanas, didžiausias Saturno ir antras didžiausias Saulės sistemos palydovas yra didesnis už Merkurijų, tačiau turįs mažesnę masę. Tai vienintelis palydovas Saulės sistemoje turįs pakankamai tankią atmosferą.[5]'),
     ('7a580a64-a414-40dc-8861-52aa79ff2255', 'Uranas','Uranas – septinta pagal nuotolį nuo Saulės planeta ir pirmoji Saulės sistemos planeta, atrasta teleskopu.[1] 1781 m. kovo 13 d. planetą atrado anglas Viljamas Heršelis. Planeta pavadinta seniausiojo graikų dievo Urano vardu. Uranas – planeta milžinė – jos skersmenyje būtų galima išrikiuoti 4 Žemės dydžio planetas, o iš planetos masės padaryti 14 Žemės dydžio planetų. Uranas skrieja 6,8 km/s greičiu ir Saulę apskrieja per 84 mūsų metus. Orbita labai ištęsta – perihelyje Uranas būna 270 mln. km arčiau Saulės negu afelyje. Planetos pusiaujo posvyris į orbitą beveik 90° laipsnių, todėl Uranas rieda tartum kamuolys, atsukdama į Saulę tai vieną, tai kitą šoną. Vienoje pusėje būna ilga diena, kitoje ilga naktis.
                                                                            Urano atmosfera susideda iš 82 % vandenilio, 15 % helio, 2 % metano, taip pat amoniako. Paviršių pastoviai dengia debesys. Jie sudaryti iš amoniako ledo, vandens ledo, metano ledo ir amonio hidrosulfido kristalėlių. Kadangi planeta skrieja 19 kartų toliau nuo Saulės negu Žemė, gauna 360 kartų mažiau šviesos ir šilumos. Išorinių debesų temperatūra siekia vos −218 °C Temperatūra planetos paviršiuje kur kas didesnė – 58 °C, tačiau beveik visame paviršiuje ji išsilaiko vienoda.
                                                                            Viršutiniai Urano debesys sudaryti daugiausia iš metano kristalėlių. Metanas sugeria geltonuosius ir raudonuosius Saulės spindulius, todėl atspindėta šviesa atrodo melsvai žalia.
                                                                            Pagal Urano sandaros teorinius modelius, po labai stora atmosfera slūgso 8000 km vandens, amoniako ir metano vandenynas, o po juo Žemės dydžio silikatinis branduolys. Temperatūra centre siekia 11000 K.
                                                                            Iki šiol Uraną aplankė tik vienas erdvėlaivis “Voyager 2”. Dabar šis erdvėlaivis jau už Saulės sistemos ribų ir tęsia kelionę į žvaigždes. 1986 m. sausio 24 d. erdvėlaivis priartėjo prie Urano ir per 6 valandas padarė 4300 planetos, jos žiedų ir palydovų nuotraukų. Buvo nustatyta, kad planetos paviršiuje siaučia smarkūs vėjai (naujausių matavimų duomenimis - iki 900 km/h[2]), sužinota, kad į erdvę Uranas išspinduliuoja 13 % daugiau šilumos, negu jos gauna iš Saulės. Tai įrodo, kad planeta turi vidinį energijos šaltinį. Uranas taip pat turi magnetinį lauką, kuris yra 2 kartus silpnesnis už Žemės magnetinį lauką.
                                                                            Uranas turi siaurų žiedų sistemą, kurios visas plotis yra apie 9000 km.[3] Žiedai buvo atrasti 1977 m. kovą Džeimso Ludlau Elioto, Edvardo V. Danhemo ir Daglaso Džono Minko. Iki 2005 pabaigos buvo identifikuota 13 Urano žiedų. Dauguma žiedų siauresni negu 10 km, sudaryti iš anglingų ~ 1 m dydžio uolienų. Dėl kai kurių palydovų gravitacijos yra kūnų, kurie visą laiką stovi vietoje.'),
     ('7a580a64-a414-40dc-8861-52aa79ff2256', 'Neptūnas','Neptūnas – Saulės sistemos išorinė planeta, aštunta pagal nuotolį nuo Saulės. Aplink Saulę skrieja elipsine orbita vidutiniu 5,4 km/s greičiu. Plika akimi yra nematomas, kadangi opozicijoje jo ryškis siekia tik 7,6 ryškio. Pro teleskopą opozicijos metu Neptūno skritulys matomas 2,5" kampu. Neptūno atmosfera susideda iš vandenilio, helio, metano, amoniako. Paviršių nuolatos dengia debesys, vėjų greitis atmosferoje siekia iki 400–700 m/s.[1] Atmosferos geometrinis albedas 50 %. Neptūno temperatūra 38 K (-235.15 pagal Celsijų). Paviršių veikiausiai dengia plonas amoniako ir metano vandenynas. Po juo yra ~3500 km storio vandens, amoniako ir metano ledų sluoksnis, centre ~20 500 km spindulio tų pačių ledų ir silikatų branduolys. Medžiagos tankis centre 4,8 g/cm³, temperatūra 12 000 K. Neptūną Vandenio žvaigždyne 1846 m. atrado J. G. Gale ~1 laipsnio nuotoliu nuo tos vietos, kurią iš Urano judėjimo trikdymų nepriklausomai vienas nuo kito apskaičiavo prancūzas U. Leverjė ir anglas Dž. Adamsas. 1989 m. pro Neptūną praskriejo JAV kosminė stotis Voyager 2.
                                                                              Neptūno vidutinis atstumas nuo Saulės – 4497 milijonai kilometrų. Apskaičiuota, kad jo atmosferos temperatūra lygi -210 °C. Neptūnas – tolimiausia Saulės sistemos planeta.
                                                                              Neptūno skersmuo – 49 500 km. Jo paros ilgumas – 16 valandų 7 minutės (patikslintas Arizonos universiteto (JAV) planetologo Ericho Karkoschkos tikslesnis paros laikas 15 val. 57 min. 59 sek.), o metai trunka 165 Žemės metus. Iš kosmoso Neptūnas atrodo mėlynas, nes jo atmosferos metanas sugeria raudoną šviesą. Didžioji Juodoji Dėmė Neptūno vandenilio, helio ir metano atmosferoje yra milžiniška – joje tilptų Žemė.');


INSERT INTO roles (name) VALUES ('USER'), ('ADMIN');
